// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class FoodyWebAppTestsTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {

        ChromeOptions options = new ChromeOptions();
        options.AddUserProfilePreference("profile.password_manager_enabled", false);
        options.AddArgument("--disable-search-engine-choice-screen");
        options.AddArgument("--headless");
        options.AddArgument("--no-sandbox");
        options.AddArgument("--disable-dev-smh-usage");
        options.AddArgument("--disable-gpu");


        driver = new ChromeDriver(options);
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Dispose();
    driver.Quit();
  }
  [Test]
  public void landingPageTests() {
    driver.Navigate().GoToUrl("http://softuni-qa-loadbalancer-2137572849.eu-north-1.elb.amazonaws.com:85/");
    driver.Manage().Window.Size = new System.Drawing.Size(1980, 1080);
    var elements = driver.FindElements(By.CssSelector(".nav-item:nth-child(1) > .nav-link"));
    Assert.True(elements.Count > 0);
    var elements2 = driver.FindElements(By.CssSelector(".nav-item:nth-child(2) > .nav-link"));
    Assert.True(elements2.Count > 0);
    var elements3 = driver.FindElements(By.CssSelector(".btn"));
    Assert.True(elements3.Count > 0);
    Assert.That(driver.Title, Is.EqualTo("Home Page - Foody.WebApp"));
  }
  [Test]
  public void loginTests() {
    driver.Navigate().GoToUrl("http://softuni-qa-loadbalancer-2137572849.eu-north-1.elb.amazonaws.com:85/");
    driver.Manage().Window.Size = new System.Drawing.Size(1980, 1080);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) > .nav-link")).Click();
    driver.FindElement(By.CssSelector("form")).Click();
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).SendKeys("Wamer");
    driver.FindElement(By.Id("password")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.Id("password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    var elements = driver.FindElements(By.CssSelector(".nav-item:nth-child(1) > .nav-link"));
    Assert.True(elements.Count > 0);
    var elements2 = driver.FindElements(By.CssSelector(".nav-item:nth-child(2) > .nav-link"));
    Assert.True(elements2.Count > 0);
    Assert.That(driver.FindElement(By.CssSelector(".masthead-subheading")).Text, Is.EqualTo("Welcome, Wamer!"));
    driver.FindElement(By.XPath("//a[@class=\'nav-link\' and text()=\'Logout\']")).Click();
    Assert.That(driver.FindElement(By.XPath("//h2[@class=\'masthead-subheading mb-0\']")).Text, Is.EqualTo("Share your homemade or store-bought food with us!"));
  }
  [Test]
  public void editProfileTest() {
    driver.Navigate().GoToUrl("http://softuni-qa-loadbalancer-2137572849.eu-north-1.elb.amazonaws.com:85/");
    driver.Manage().Window.Size = new System.Drawing.Size(1980, 1080);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) > .nav-link")).Click();
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).SendKeys("Wamer");
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".fa-user > path")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".col-xl-10")).Click();
        driver.FindElement(By.Id("FirstName")).Clear();
        driver.FindElement(By.Id("FirstName")).SendKeys("Edited");
    driver.FindElement(By.CssSelector(".card-body")).Click();
        driver.FindElement(By.Id("MiddleName")).Clear();
        driver.FindElement(By.Id("MiddleName")).SendKeys("Edited");
    driver.FindElement(By.CssSelector(".gradient-form")).Click();
        driver.FindElement(By.Id("LastName")).Clear();
        driver.FindElement(By.Id("LastName")).SendKeys("Edited");
    driver.FindElement(By.Id("About")).Click();
        driver.FindElement(By.Id("About")).Clear();
        driver.FindElement(By.Id("About")).SendKeys("Random about me ");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-sm-9 > .text-muted")).Text, Is.EqualTo("Edited Edited Edited"));
    Assert.That(driver.FindElement(By.CssSelector(".col-md-6:nth-child(1) .mb-1")).Text, Is.EqualTo("Random about me"));
    driver.FindElement(By.LinkText("Logout")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".masthead-subheading")).Text, Is.EqualTo("Share your homemade or store-bought food with us!"));
  }
}
