name: Foody Web App Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'    

      - name: Install dependencies
        run: dotnet restore 

      - name: Build
        run: dotnet build --no-restore

      - name: Run .NET tests
        run: dotnet test --verbosity normal

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Selenium IDE CLI
        run: npm install -g selenium-side-runner

      - name: Run Selenium IDE tests
        run: selenium-side-runner LogInEditProfileTests.side